dashboard/category/urls.py
from django.conf.urls import url
from dashboard.category import views

urlpatterns = [
    url(r'^$', views.CategoryList.as_view(), name='category_list'),
    url(r'^create/$', views.CategoryCreate.as_view(), name='category_create'),
]

dashboard/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList.as_view(), name='product_list'),
    url(r'^create/$', views.create, name='product_create'),
]

dashboard/urls.py
from django.conf.urls import url, include
from dashboard import views
from .product.urls import urlpatterns as product_urls
from .category.urls import urlpatterns as category_urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product/', include(product_urls)),
    url(r'^category/', include(category_urls)),
]

matjar/urls.py
from django.conf.urls import url
from matjar import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

matjar_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from matjar import views
from dashboard.urls import urlpatterns as dashboard_urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^matjar/', include('matjar.urls')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^admin/', admin.site.urls),
]

dashboard/models.py
from django.db import models

# Create your models here.

matjar/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit


# Create your models here.
class Category(models.Model):
    name = models.CharField('اسم الصنف', max_length=50)

    def __str__(self):
        return "Category ID: {}".format(self.id)


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_published = models.BooleanField(default=False)
    show_on_homepage = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "Product# {}".format(self.id)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='product_images')
    image_title = models.CharField(max_length=100)
    image_description = models.CharField(max_length=500)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    thumbnail = ImageSpecField(source=image,
                               processors=[ResizeToFit(100, 100)],
                               format='JPEG',
                               options={'quality': 60})

    medium = ImageSpecField(source=image,
                            processors=[ResizeToFit(320, 150)],
                            format='JPEG',
                            options={'quality': 60})

    large = ImageSpecField(source=image,
                           processors=[ResizeToFit(580, 420)],
                           format='JPEG',
                           options={'quality': 60})


class Order(models.Model):
    created = models.DateTimeField(default=now, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
    )
    anonymous_user_email = models.EmailField(
        blank=True,
        default='',
        editable=False,
    )
    items = models.ManyToManyField(Product, through='OrderItem')


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField()

dashboard/category/forms.py
from django import forms
from matjar.models import Category


# class CategoryForm(forms.ModelForm):
#     class Meta:
#         model = Category
#         fields = ['name']

dashboard/product/forms.py
from django import forms
from matjar.models import Category, Product


class ProductForm(forms.Form):
    name = forms.CharField(label='اسم المنتج', max_length=100)
    category = forms.ModelChoiceField(label='التصنيف', queryset=Category.objects.all(), empty_label='اختر من القائمة')
    description = forms.CharField(label='الوصف', max_length=500)
    price = forms.DecimalField(label='السعر', max_digits=10, decimal_places=2)
    published = forms.BooleanField(label='عرض المنتج في الموقع', required=False)
    show_on_homepage = forms.BooleanField(label='اعرض في الصفحة الرئيسية',required=False)
    image = forms.ImageField(label='صور للمنتج')

    class Meta:
        model = Product

dashboard/category/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# from dashboard.category.forms import CategoryForm
from django.views.generic import ListView
from django.views.generic.edit import CreateView, FormView
from matjar.models import Category


# def index(request):
#     return render(request, 'dashboard/category/category_list.html')


class CategoryList(ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'dashboard/category/category_list.html'


# def create(request):
#     if request.method == 'POST':
#         form = CategoryForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/dashboard/category/')
#
#     else:
#         form = CategoryForm()
#
#     return render(request, 'dashboard/category/category_create.html', {'form': form})


class CategoryCreate(CreateView):
    model = Category
    fields = ['name']
    template_name = 'dashboard/category/category_create.html'
    success_url = '/dashboard/category/'

dashboard/product/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ProductForm
from django.views.generic import ListView
from matjar.models import Product


# def index(request):
#     return render(request, 'dashboard/product/product_list.html', {})


class ProductList(ListView):
    model = Product
    template_name = 'dashboard/product/product_list.html'
    context_object_name = 'product_list'


def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponse('The product has been saved.')

    form = ProductForm()
    return render(request, 'dashboard/product/create.html', {'form': form})

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'dashboard/index.html', {})

matjar/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse("Hello World! - This is Matjar Main App")

dashboard/templates/dashboard/__base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ar">

<head>
    {% block meta_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock %}

    <title>{% block title %}Simple Sidebar - Start Bootstrap Template{% endblock %}</title>
    {% block stylesheets %}
        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
              crossorigin="anonymous">

        <!-- Bootstrap RTL CSS -->
        <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">

        <!-- Bootstrap Optional Theme CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
              integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r"
              crossorigin="anonymous">

        <!-- Custom CSS -->
        <link href="{% static "dashboard/css/base.css" %}" rel="stylesheet">
    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">



    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    {% block content %}
                        <h1>Simple Sidebar</h1>
                        <p>This template has a responsive menu toggling system. The menu will appear collapsed on
                            smaller
                            screens, and will appear non-collapsed on larger screens. When toggled using the button
                            below,
                            the menu will appear/disappear. On small screens, the page content will be pushed off
                            canvas.</p>
                        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a href="/dashboard/">متجر - إدارة المبيعات</a>
            </li>
            <li>
                <a href="#">الطلبات</a>
            </li>
            <li>
                <a href="{% url 'dashboard:product_list' %}">المنتجات</a>
            </li>
            <li>
                <a href="#">التصميم</a>
            </li>
            <li>
                <a href="#">إعدادات المتجر</a>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->



</div>
<!-- /#wrapper -->
{% block javascript %}
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">

        <!-- Bootstrap Core JavaScript -->
        <
        script
        src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity = "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin = "anonymous" ></script>

{% endblock %}
</body>

</html>

dashboard/templates/dashboard/category/category_create.html
{% extends "dashboard/__base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Category List
{% endblock title %}

{% block content %}
    <form action="." method="post">
    {% csrf_token %}
    {{ form | crispy}}
        <input type="submit" name="submit" value="حفظ" class="btn btn-info">
    </form>
{% endblock content %}

dashboard/templates/dashboard/category/category_list.html
{% extends "dashboard/__base.html" %}
{% block title %}
    Category List
{% endblock title %}

{% block content %}
    <a class="btn btn-default" href="{% url 'dashboard:category_create' %}" role="button">صنف جديد</a>
    <h2>قائمة الأصناف</h2>
    <ul>
        {% for category in category_list %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends "dashboard/__base.html" %}

dashboard/templates/dashboard/product/create.html
{% extends "dashboard/__base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Product List
{% endblock title %}

{% block content %}
    <form action="/dashboard/product/create" method="post">
    {% csrf_token %}
    {% crispy form %}
        <input type="submit" value="حفظ">
    </form>
{% endblock content %}

dashboard/templates/dashboard/product/product_list.html
{% extends "dashboard/__base.html" %}
{% block title %}
    Category List
{% endblock title %}

{% block content %}
    <a class="btn btn-default" href="{% url 'dashboard:category_create' %}" role="button">منتج جديد</a>
    <h2>قائمة المنتجات</h2>
    <table>
        <tr>
            <th>#</th>
            <th>اسم المنتج</th>
            <th>الصنف</th>
            <th>السعر</th>

        </tr>
    </table>
{% endblock content %}